[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "../Backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/vibe-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
